[2024-08-26T07:30:41.756+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-26T07:30:42.175+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrap_to_dag.scrape_oto scheduled__2024-08-25T00:00:00+00:00 [queued]>
[2024-08-26T07:30:42.186+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrap_to_dag.scrape_oto scheduled__2024-08-25T00:00:00+00:00 [queued]>
[2024-08-26T07:30:42.187+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-26T07:30:42.200+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): scrape_oto> on 2024-08-25 00:00:00+00:00
[2024-08-26T07:30:42.205+0700] {standard_task_runner.py:64} INFO - Started process 115450 to run task
[2024-08-26T07:30:42.214+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'scrap_to_dag', 'scrape_oto', 'scheduled__2024-08-25T00:00:00+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/oto/scrap_oto.py', '--cfg-path', '/tmp/tmpe3mf2rjk']
[2024-08-26T07:30:42.221+0700] {standard_task_runner.py:91} INFO - Job 127: Subtask scrape_oto
[2024-08-26T07:30:42.337+0700] {task_command.py:426} INFO - Running <TaskInstance: scrap_to_dag.scrape_oto scheduled__2024-08-25T00:00:00+00:00 [running]> on host BrightHorizons.
[2024-08-26T07:30:42.442+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrap_to_dag' AIRFLOW_CTX_TASK_ID='scrape_oto' AIRFLOW_CTX_EXECUTION_DATE='2024-08-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-25T00:00:00+00:00'
[2024-08-26T07:30:42.443+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-26T07:30:42.459+0700] {logging_mixin.py:188} INFO - Fetching data for price category: dibawah-30-juta on date: 2024-08-26
[2024-08-26T07:30:42.799+0700] {logging_mixin.py:188} INFO - Fetching page 1 of 5 for price category: dibawah-30-juta
[2024-08-26T19:28:02.529+0700] {local_task_job_runner.py:313} WARNING - State of this instance has been externally set to up_for_retry. Terminating instance.
[2024-08-26T19:28:02.530+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-26T19:28:02.533+0700] {process_utils.py:132} INFO - Sending 15 to group 115450. PIDs of all processes in the group: [115450]
[2024-08-26T19:28:02.533+0700] {process_utils.py:87} INFO - Sending the signal 15 to group 115450
[2024-08-26T19:28:02.534+0700] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-08-26T19:28:02.534+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-26T19:28:02.547+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/miracle/mobil/scrape/script/oto/oto_scrape.py", line 82, in oto_scrape
    page_response = fetch_data_with_retries(base_url, params, headers)
  File "/home/miracle/mobil/scrape/script/oto/oto_scrape.py", line 40, in fetch_data_with_retries
    response = requests.get(url, params=params, headers=headers)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 1060, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1100, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1371, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-08-26T19:28:02.554+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=scrap_to_dag, task_id=scrape_oto, run_id=scheduled__2024-08-25T00:00:00+00:00, execution_date=20240825T000000, start_date=20240826T003042, end_date=20240826T122802
[2024-08-26T19:28:02.586+0700] {process_utils.py:80} INFO - Process psutil.Process(pid=115450, status='terminated', exitcode=2, started='07:30:41') (115450) terminated with exit code 2
