[2024-08-04T20:23:51.509+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-04T20:23:51.647+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrap_to_dag.scrape_oto manual__2024-08-04T13:19:56.241241+00:00 [queued]>
[2024-08-04T20:23:51.658+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrap_to_dag.scrape_oto manual__2024-08-04T13:19:56.241241+00:00 [queued]>
[2024-08-04T20:23:51.659+0700] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-08-04T20:23:51.679+0700] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): scrape_oto> on 2024-08-04 13:19:56.241241+00:00
[2024-08-04T20:23:51.684+0700] {standard_task_runner.py:64} INFO - Started process 9896 to run task
[2024-08-04T20:23:51.688+0700] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'scrap_to_dag', 'scrape_oto', 'manual__2024-08-04T13:19:56.241241+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/oto/scrap_oto.py', '--cfg-path', '/tmp/tmp990z0e7r']
[2024-08-04T20:23:51.690+0700] {standard_task_runner.py:91} INFO - Job 12: Subtask scrape_oto
[2024-08-04T20:23:51.766+0700] {task_command.py:426} INFO - Running <TaskInstance: scrap_to_dag.scrape_oto manual__2024-08-04T13:19:56.241241+00:00 [running]> on host BrightHorizons.
[2024-08-04T20:23:51.903+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrap_to_dag' AIRFLOW_CTX_TASK_ID='scrape_oto' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T13:19:56.241241+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-04T13:19:56.241241+00:00'
[2024-08-04T20:23:51.904+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-04T20:23:51.919+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-04T20:23:51.919+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/miracle/mobil/scrape/script/oto/oto_scrape.py", line 12, in oto_scrape
    config = json.load(open('config.json'))
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
[2024-08-04T20:23:51.936+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=scrap_to_dag, task_id=scrape_oto, run_id=manual__2024-08-04T13:19:56.241241+00:00, execution_date=20240804T131956, start_date=20240804T132351, end_date=20240804T132351
[2024-08-04T20:23:51.954+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task scrape_oto ([Errno 2] No such file or directory: 'config.json'; 9896)
[2024-08-04T20:23:51.982+0700] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-04T20:23:52.009+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-04T20:23:52.013+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
